### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas' - when running "merge_tb_data.py"

### ISSUE THREAD

**Issue by bsalehe** [cambiotraining/bacterial-genomics#13]
Hi @avantonder and @tavareshugo  I am trying to run `merge_tb_data.py`. The command is `python scripts/merge_tb_data.py -s sample_info.csv -t preprocessed/tb-profiler/Nam_TB.txt`. I am experiencing this error:- 

> Traceback (most recent call last):
  File "/home/ubuntu/Course_Materials/M_tuberculosis/scripts/merge_tb_data.py", line 7, in <module>
    import pandas as pd

I tried to change two conda environments accordingly which seem to have pandas; `tb-profiler` and `seqtk` based on the instructions given [here](https://github.com/cambiotraining/bacterial-genomics/issues/2#issuecomment-1803623523). But neither seem working. Should we have a separate pandas environment for this? I haven't tried it though! 

Cheers

**Comment by tavareshugo** [comment]
I believe the `mamba activate tb-profiler` environment should have pandas installed.

**Comment by avantonder** [comment]
Yes, tb-profiler environment needs pandas installed. I use it when running python scripts later on

**Comment by bsalehe** [comment]
Eventually the script worked with `seqtk` env but not tb-profiler.

Cheers
