### ISSUE TITLE
Adding -resume for each nextflow script

### ISSUE THREAD

**Issue by bsalehe** [cambiotraining/bacterial-genomics#14]
@tavareshugo  and @avantonder would it be worth adding `-resume` for each of the nextflow scripts. For the sake of time when the pipeline fails no need to rerun all processes, just to resume where it stopped. I realised all of the nextflow scripts missed this.

Thanks

**Comment by avantonder** [comment]
Yes, this is a good idea - I add it to the scripts when I ran them
