### ISSUE TITLE
Install pandas in base environment

### ISSUE THREAD

**Issue by bsalehe** [cambiotraining/bacterial-genomics#15]
Hi @tavareshugo and @avantonder. I wonder if we could install pandas in the base or in its own env as many other python scripts depend on the pandas downstream for instances `seqtk_parser.py` or `merge_pneumo_data.py`. As I have finished testing all scripts for all three isolates, I was consistently getting the pandas package not found error when I ran these scripts. I had to activate `seqtk` env which seems to have pandas installed to be able to run the scripts.

Thanks

**Comment by tavareshugo** [comment]
Yes, we can still update software. I'll make a note to Paul

**Comment by tavareshugo** [comment]
Fixed in 0606e1e899627aee13e0807ee57184ba1a8d0fb3
