### ISSUE TITLE
Problem with nf-core/fetchngs version 1.12.0 downloading files using ftp

### ISSUE THREAD

**Issue by bsalehe** [cambiotraining/bacterial-genomics#29]
Some participants if not all experienced the weird unnoticed error when they were running [nf-core/fetchngs version 1.12.0](https://nf-co.re/fetchngs/1.12.0/). By default the tool download using the ftp method. To avoid this error, the parameter `--download_method` need be changed to sratools in the fetchngs.sh script.

> nextflow run nf-core/fetchngs \
>  -profile singularity \
>  --max_memory '16.GB' --max_cpus 8 \
>  --input SAMPLES \
>  --outdir results/fetchngs \
>  --nf_core_pipeline viralrecon \
>  `--download_method sratools

**Comment by avantonder** [comment]
I've updated the course materials so this should be fixed now. The script still needs to be updated
