### ISSUE TITLE
Renaming `fas` files in 02-pseudogenome_check.sh

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/bacterial-genomics#4]
I'm wondering why is it necessary to rename the files in the script `02-pseudogenome_check.sh`?

We have this line: 

```bash
# rename aligned_pseudogenomes.fas
mv $fasta_dir/aligned_pseudogenomes.fas $fasta_dir/aligned_pseudogenomes.fasta
```

And then at the end: 

```bash
# rename aligned_pseudogenomes.fas
mv $fasta_dir/aligned_pseudogenomes.fasta $fasta_dir/aligned_pseudogenomes.fas
```

The issue is that if the script fails in-between these two lines of code (as it did for me, due to missing the parser python script on my path), then the files will be renamed and the script will fail the second time around.

**Comment by tavareshugo** [comment]
I've muddled things so much, that I'm having to re-run bactmap, just to be sure I have the right input files downstream. 
If the file extension change is necessary for one of the tools used, then I would recommend making a symbolic link to the original file in the `${outdir}` directory, and then remove the symbolic link at the end. That way we make sure not to corrupt any of the input data necessary for the script.

**Comment by avantonder** [comment]
It was to stop the file  being included in the for loop so not really necessary to change it (seemed like the laziest way to do this!). Happy to go with an alternative suggestion.

**Comment by tavareshugo** [comment]
I see. 
In that case maybe we can do: 

```bash
for filepath in $(ls $fasta_dir/*.fas | grep -v "aligned_genomes")
```

**Comment by tavareshugo** [comment]
this latter solution works
