### ISSUE TITLE
Script edit

### ISSUE THREAD

**Issue by avantonder** [cambiotraining/bacterial-genomics#8]
@tavareshugo  Hopefully the last script that needs editing. It makes sense to use the preprocessed data for the pairwise snp matrix calculation so `07-run_pairsnp.sh` in `M_tuberculosis/scripts` needs to be edited:

change `snp_file="results/snp-sites/aligned_pseudogenomes_masked_snps.fas"` to `snp_file="preprocessed/snp-sites/aligned_pseudogenomes_masked_snps.fas"`

**Comment by avantonder** [comment]
@tavareshugo It looks like only one script explicitly uses the preprocessed data:

`./M_tuberculosis/scripts/07-run_pairsnp.sh`

For a second script, the exercise states that you can use either the preprocessed data or wait for panaroo to finish:

`./S_aureus/scripts/03-run_iqtree.sh`

We may want to change this so the participants wait for panaroo and build a tree based on the five genome dataset though I don't expect running IQ-TREE on the 30 genome core gene alignment will take that long

I noticed that the samplesheet we prepare for funcscan will include all 50 assemblies meaning funcscan will take too long. I need to change the text to add in an instruction to only run funcscan on 5 assemblies.

**Comment by tavareshugo** [comment]
I've updated this script on our dropbox files
